//constants for the Blogs
export const postsConstants = {
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",
  GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
  GET_ALL_POSTS_FAIL: "GET_ALL_POSTS_FAIL",
  CREATE_POSTS_SUCCESS: "CREATE_POSTS_SUCCESS",
  CREATE_POSTS_FAIL: "CREATE_POSTS_FAIL",
  POSTS_EDIT_SUCCESS: "POSTS_EDIT_SUCCESS",
  POSTS_EDIT_FAIL: "POSTS_EDIT_FAIL",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_FAIL: "DELETE_POSTS_FAIL",
  LOADING_POSTS: "LOADING_POSTS",
  CLEAR_EDIT_POSTS: "CLEAR_EDIT_POSTS",
  UPDATE_POSTS_SUCCESS: "UPDATE_POSTS_SUCCESS",
  UPDATE_POSTS_FAIL: "UPDATE_POSTS_FAIL",
  LOADING_UPDATED: "LOADING_UPDATED",
  CLEAR_ALL_DATA: "CLEAR_ALL_DATA",
};
